name: day3-scm-vistreportsapi

on:
  push:
    branches:
      - master
    paths:
      - day3/apps/infrastructure/bicep/visitreports/**
      - day3/apps/nodejs/visitreport/**
      - day3/apps/nodejs/textanalytics/**
      - .github/workflows/day3-scm-visitreportsapi.yml

  pull_request:
    branches:
      - master
    paths:
      - day3/apps/infrastructure/bicep/visitreports/**
      - day3/apps/nodejs/visitreport/**
      - day3/apps/nodejs/textanalytics/**
      - .github/workflows/day3-scm-visitreportsapi.yml

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '12.x'
      API_PACKAGE_NAME: 'scmvisitreportsapi.zip'
      TA_PACKAGE_NAME: 'textanalytics.zip'
      NEED_DEPLOY: ${{ (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Transpile bicep files
        run: az bicep build -f ./day3/apps/infrastructure/bicep/visitreports/visitreportsmain.bicep

      - name: Archive ARM Templates artifacts
        uses: actions/upload-artifact@v2
        if: env.NEED_DEPLOY == 'true'
        with:
          name: bicep
          path: ./day3/apps/infrastructure/bicep/visitreports/visitreportsmain.json
          retention-days: 30

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install VisitReport
        working-directory: ./day3/apps/nodejs/visitreport
        run: |
          npm install

      - name: zip VisitReport
        working-directory: ./day3/apps/nodejs/visitreport
        run: |
          zip -r ${{ env.API_PACKAGE_NAME }} ./*

      - name: Archive VisitReports
        uses: actions/upload-artifact@v2
        if: env.NEED_DEPLOY == 'true'
        with:
          name: scmvisitrepportsapi
          path: './day3/apps/nodejs/visitreport/${{ env.API_PACKAGE_NAME }}'
          retention-days: 30

      - name: npm install TextAnalytics
        working-directory: ./day3/apps/nodejs/textanalytics
        run: |
          npm install

      - name: zip TextAnalytics
        working-directory: ./day3/apps/nodejs/textanalytics
        run: |
          zip -r ${{ env.TA_PACKAGE_NAME }} ./*

      - name: Archive TextAnalytics
        uses: actions/upload-artifact@v2
        if: env.NEED_DEPLOY == 'true'
        with:
          name: textanalytics
          path: './day3/apps/nodejs/textanalytics/${{ env.TA_PACKAGE_NAME }}'
          retention-days: 30

  deploy-to-dev:
    if: (github.repository == 'azuredevcollege/trainingdays') && ((github.event_name == 'push') || (github.event_name == 'workflow_dispatch'))
    runs-on: ubuntu-latest
    environment: day3-scm-dev
    needs: build
    env:
      RESOURCE_GROUP_NAME: rg-scm-devday3
      RESOURCE_GROUP_LOCATION: westeurope
      API_PACKAGE_NAME: 'scmvisitreportsapi.zip'
      TA_PACKAGE_NAME: 'textanalytics.zip'
      ENV_NAME: devd3

    steps:
      - name: Download bicep artifacts
        uses: actions/download-artifact@v2
        with:
          name: bicep

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create ResourceGroup if it does not exist
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            if $(az group exists --name ${{ env.RESOURCE_GROUP_NAME }}) ; then
              echo "Azure resource group already exists, skipping creation..."
            else
              az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.RESOURCE_GROUP_LOCATION }}
              echo "Azure resource group created"
            fi

      - name: Deploy infrastructure to dev environment
        uses: azure/arm-deploy@v1
        id: infrastructure
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./visitreportsmain.json
          parameters: env=${{ env.ENV_NAME }}

      - name: Download VisitReports artifacts
        uses: actions/download-artifact@v2
        with:
          name: scmvisitrepportsapi

      - name: Deploy SCM Visitreports API
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.infrastructure.outputs.visitreportsWebAppName }}
          package: ./${{ env.API_PACKAGE_NAME }}

      - name: Download textAnalytics artifacts
        uses: actions/download-artifact@v2
        with:
          name: textanalytics

      - name: Deploy Textanalytics
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ steps.infrastructure.outputs.textanalyticsFunctionName }}
          package: ./${{ env.TA_PACKAGE_NAME }}

  deploy-to-test:
    if: (github.repository == 'azuredevcollege/trainingdays') && ((github.event_name == 'push') || (github.event_name == 'workflow_dispatch'))
    runs-on: ubuntu-latest
    environment: day3-scm-test
    needs: deploy-to-dev
    env:
      RESOURCE_GROUP_NAME: rg-scm-testday3
      RESOURCE_GROUP_LOCATION: westeurope
      API_PACKAGE_NAME: 'scmvisitreportsapi.zip'
      TA_PACKAGE_NAME: 'textanalytics.zip'
      ENV_NAME: testd3

    steps:
      - name: Download bicep artifacts
        uses: actions/download-artifact@v2
        with:
          name: bicep

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create ResourceGroup if it does not exist
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            if $(az group exists --name ${{ env.RESOURCE_GROUP_NAME }}) ; then
              echo "Azure resource group already exists, skipping creation..."
            else
              az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.RESOURCE_GROUP_LOCATION }}
              echo "Azure resource group created"
            fi

      - name: Deploy infrastructure to dev environment
        uses: azure/arm-deploy@v1
        id: infrastructure
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./visitreportsmain.json
          parameters: env=${{ env.ENV_NAME }}

      - name: Download VisitReports artifacts
        uses: actions/download-artifact@v2
        with:
          name: scmvisitrepportsapi

      - name: Deploy SCM Visitreports API
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.infrastructure.outputs.visitreportsWebAppName }}
          package: ./${{ env.API_PACKAGE_NAME }}

      - name: Download textAnalytics artifacts
        uses: actions/download-artifact@v2
        with:
          name: textanalytics

      - name: Deploy Textanalytics
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ steps.infrastructure.outputs.textanalyticsFunctionName }}
          package: ./${{ env.TA_PACKAGE_NAME }}
